### ISSUE TITLE
Towers don't always seem to target furthest enemy

### ISSUE THREAD

**Issue by cb299792458** [project-brooklyn/project-brooklyn#38]

**Comment by rockokw** [comment]
Oh, didn't you want them to target the closest enemy or was that just for the arrow tower?

**Comment by cb299792458** [comment]
Oh is that what it's doing? I think that if the fire rate isn't tied to projectile travel time, it's usually best for the tower to target the enemy that's furthest (along the path) i.e. closest to the base.

**Comment by rockokw** [comment]
Oh, I see what you mean, that's an interesting behavior. I think the most intuitive thing is to have it target the enemy that's closet to the tower itself.

We could also consider a feature where the player can customize target priority either globally or per tower, something like what Bloons has: https://bloons.fandom.com/wiki/Targeting_Priority?file=FirstLastCloseStrong_BTD6.png#Bloons_TD_6

**Comment by cb299792458** [comment]
Towers now target furthest/oldest enemy. We can reopen to allow for more targeting options.
