### ISSUE TITLE
Option to sell tower

### ISSUE THREAD

**Issue by rockokw** [project-brooklyn/project-brooklyn#64]
This came up in play test with Fred. Player may want to remove a tower.

Currently there's no way for a tower to be destroyed either, so they're permanent. Need to discuss if there would be a refund and how much.

**Comment by rockokw** [comment]
Yea, agreed. PR #63 is meant for the context of a single build phase while this one is for a subsequent build phase from the one in which the tower was built

**Comment by cb299792458** [comment]
Sounds good. Feel free to assign one to me if you want to handle one yourself.
