### ISSUE TITLE
Clean Up BuyMenu

### ISSUE THREAD

**Issue by cb299792458** [project-brooklyn/project-brooklyn#66]
BuyMenu is a little too long, as uses plain r3f <Text>, a custom button that respondson click and hover would be better.
Tiles can only be selected if they are on top, but it's still tricky if there are other top tiles "behind" the first from the camera's POV. It would be best if the tile "closest" to the camera were always selected on first click.

**Comment by rockokw** [comment]
Regarding the buy menu, I was thinking we should consider rendering it in HTML instead. It was convenient for prototyping but I'm not sure if it makes sense to keep it in the camera view.

**Comment by cb299792458** [comment]
Yeah, HTML will be much easier to read and click. We can chat about this later, but most of the game info and menus could be moved to the sides or something.

**Comment by cb299792458** [comment]
Covered by #75
