### ISSUE TITLE
Add Level Info to HTML UI

### ISSUE THREAD

**Issue by cb299792458** [project-brooklyn/project-brooklyn#80]
During DEFEND, display some info, such as enemy type/name, and number of enemies left.

Optionally, towers may still be selectable during DEFEND to view SelectedTowerInfo.

**Comment by cb299792458** [comment]
I forgot to checkout a feature branch again T_T

**Comment by cb299792458** [comment]
Level info needs some design work, then lots of css.

**Comment by rockokw** [comment]
> I forgot to checkout a feature branch again T_T

Ok, fixed and moved your two commits to `brian/opps`. I think the issue might be that we're admins. I enabled another setting for `main` that should resolve it.

![image](https://github.com/user-attachments/assets/6b34d6af-09f0-436f-b70a-3bc5ca4ae4b2)
